runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START gae_flex_mailjet_yaml]
env_variables:
    MAILJET_API_KEY: your-mailjet-api-key
    MAILJET_API_SECRET: your-mailjet-api-secret
    MAILJET_SENDER: your-mailjet-sender-address
# [END gae_flex_mailjet_yaml]
