runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: .*
  script: main.app

# [START env_variables]
env_variables:
    MAILJET_API_KEY: your-mailjet-api-key
    MAILJET_API_SECRET: your-mailjet-api-secret
    MAILJET_SENDER: your-mailjet-sender-address
# [END env_variables]
