runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START gae_flex_python_redis_yaml]
env_variables:
    REDIS_HOST: your-redis-host
    REDIS_PORT: your-redis-port
    REDIS_PASSWORD: your-redis-password
# [END gae_flex_python_redis_yaml]
