runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START gae_flex_twilio_env]
env_variables:
    TWILIO_ACCOUNT_SID: your-account-sid
    TWILIO_AUTH_TOKEN: your-auth-token
    TWILIO_NUMBER: your-twilio-number
# [END gae_flex_twilio_env]
