runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START env_variables]
env_variables:
    MAILGUN_DOMAIN_NAME: your-mailgun-domain-name
    MAILGUN_API_KEY: your-mailgun-api-key
# [END env_variables]
