runtime: python27
api_version: 1
threadsafe: true

builtins:
# Deferred is required to use google.appengine.ext.deferred.
- deferred: on

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
